global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs'
    static_configs:
      - targets: ['nodejs:3000']   

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

